// GET/POST /login is the one REQUIREMENTS §7.2 route group M1 can serve for
// real: /authorize, which would hand login a continuation target, is phase 2
// (REQUIREMENTS §11), so a successful login with no login_challenge has
// nowhere else to send the browser yet and renders a static placeholder
// instead of redirecting.
package main

import (
	"errors"
	"html/template"
	"log/slog"
	"net/http"
	"net/url"
	"time"

	"github.com/JonasBorgesLM/moat/csrf"
	"github.com/JonasBorgesLM/moat/secureheaders"
	"github.com/JonasBorgesLM/usher/internal/audit"
	"github.com/JonasBorgesLM/usher/internal/identity"
	"github.com/JonasBorgesLM/usher/internal/session"
)

// genericLoginError is RS-14/RS-25's point: the same message whether the
// identifier does not exist or the password is wrong, so the response gives
// an attacker nothing to distinguish the two.
const genericLoginError = "invalid identifier or password"

// loginHandler serves GET and POST /login. Its fields are exactly what
// login needs — identity.Authenticator for RS-14's constant-work check,
// session.SessionStore and the CSRF protector for RS-12b's dual rotation
// (session.RotateLogin, built in #20), and session.ChallengeStore only to
// thread a login_challenge through once /authorize exists to issue one.
type loginHandler struct {
	auth       *identity.Authenticator
	sessions   session.SessionStore
	challenges session.ChallengeStore
	protector  *csrf.Protector
	emitter    audit.Emitter // RF-09; nil is valid and simply emits nothing
	issuer     string        // RS-29, carried on a prompt=none login_required redirect (ADR-0020)

	idleTTL, absoluteTTL time.Duration
	now                  func() time.Time

	loginTmpl    *template.Template
	loggedInTmpl *template.Template

	logger *slog.Logger
}

// loginPageData is login.html.tmpl's input. Every field here is either
// generated by this binary (CSRFToken, Nonce) or passed through unchanged
// from this same request's own prior render (Challenge, an opaque id this
// binary issued) — RS-36's "never wrap outside data in template.HTML"
// concern is about data that reaches the template from a different origin's
// registration (a client's name, a requested scope), which this page does
// not render; see internal/session's Challenge type and consent's future
// handler for where that concern actually applies.
type loginPageData struct {
	CSRFToken string
	Nonce     string
	Challenge string
	Error     string
}

// get is RF-10/RF-11's own decision point (ADR-0020): with no
// login_challenge, behavior is unchanged from M1 -- there is no OIDC
// request here to apply prompt/max_age against. With one, and only if the
// challenge itself still resolves, it checks whether the browser already
// carries a session that satisfies this specific request before falling
// back to rendering the form -- the same silent-completion shape
// consent.go's own serve already uses for RF-13's consent skip, applied
// here to login.
//
// An unresolvable challenge (unknown or expired) renders the form exactly
// as it did before this method existed: the POST that follows will fail
// against the same challenge, the same outcome this already produced.
func (h *loginHandler) get(w http.ResponseWriter, r *http.Request) {
	challengeID := r.URL.Query().Get("login_challenge")
	if challengeID == "" {
		h.render(w, r, loginPageData{})
		return
	}

	challenge, err := h.challenges.Get(r.Context(), challengeID)
	if err != nil {
		h.render(w, r, loginPageData{Challenge: challengeID})
		return
	}

	sess, hasSession := h.existingSession(r)
	if h.needsFreshAuthentication(challenge, sess, hasSession) {
		if challenge.Prompt == "none" {
			// RS-29's own issuer, carried on this error the same as every
			// other /authorize-originated redirect. onParseError is
			// defensive only: challenge.RedirectURI already passed
			// exactRedirectURIMatch when /authorize created this
			// challenge (RS-28).
			redirectOAuthError(w, r, h.logger, h.issuer, challenge.RedirectURI, challenge.State,
				"login_required", "",
				func(string) { http.Error(w, "internal error", http.StatusInternalServerError) })
			return
		}
		h.render(w, r, loginPageData{Challenge: challengeID})
		return
	}

	// Silent reuse: a session already satisfies this request (RF-10) --
	// prompt never asked for login, and max_age, if present, is still
	// satisfied. authTime is the session's own, unchanged: a reused
	// session does not get a fresher auth_time than the login that
	// actually produced it.
	h.proceedToConsent(w, r, challengeID, sess.Subject, sess.AuthTime)
}

// existingSession reports the browser's current session, if its cookie
// names one that is still live. Both failure modes -- no cookie, or a
// cookie session.SessionStore no longer recognizes -- collapse to
// hasSession=false: this call site only ever asks "is there something to
// reuse," never why there is not.
func (h *loginHandler) existingSession(r *http.Request) (sess session.BrowserSession, hasSession bool) {
	rawID, err := session.RawSessionID(r)
	if err != nil {
		return session.BrowserSession{}, false
	}
	sess, err = h.sessions.Get(r.Context(), rawID)
	if err != nil {
		return session.BrowserSession{}, false
	}
	return sess, true
}

// needsFreshAuthentication is RF-11's own three conditions, any one of
// which forces the login form regardless of what prompt=none would
// otherwise skip: no usable session at all, prompt=login overriding one
// that does exist, or max_age naming a window sess.AuthTime no longer
// falls inside of.
func (h *loginHandler) needsFreshAuthentication(challenge session.Challenge, sess session.BrowserSession, hasSession bool) bool {
	if !hasSession {
		return true
	}
	if challenge.Prompt == "login" {
		return true
	}
	if challenge.MaxAge != nil && h.now().Sub(sess.AuthTime) > *challenge.MaxAge {
		return true
	}
	return false
}

// proceedToConsent is login's own half of the login->consent hand-off,
// shared by a fresh password login (completeLogin) and a silent reuse
// (get): record the authenticated subject and its auth_time on the
// challenge (RF-11's auth_time claim is this value, carried unchanged
// from here to oauth.Code in consent.go), then redirect to /consent.
func (h *loginHandler) proceedToConsent(w http.ResponseWriter, r *http.Request, challengeID, subject string, authTime time.Time) {
	if err := h.challenges.SetAuthenticated(r.Context(), challengeID, subject, authTime); err != nil {
		h.logger.ErrorContext(r.Context(), "login: set challenge authenticated", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	http.Redirect(w, r, "/consent?login_challenge="+url.QueryEscape(challengeID), http.StatusSeeOther)
}

func (h *loginHandler) post(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad request", http.StatusBadRequest)
		return
	}
	challenge := r.PostForm.Get("login_challenge")
	identifier := r.PostForm.Get("identifier")
	password := r.PostForm.Get("password")
	canonical := identity.CanonicalizeIdentifier(identifier)

	result, err := h.auth.Attempt(r.Context(), identifier, password)
	switch {
	case err == nil:
		h.emit(r, audit.EventLoginAttempt, audit.OutcomeSuccess, canonical)
	case errors.Is(err, identity.ErrRateLimited):
		h.emit(r, audit.EventRateLimited, audit.OutcomeFailure, canonical)
		w.WriteHeader(http.StatusTooManyRequests)
		h.render(w, r, loginPageData{Challenge: challenge, Error: genericLoginError})
		return
	case errors.Is(err, identity.ErrLoginFailed):
		h.emit(r, audit.EventLoginAttempt, audit.OutcomeFailure, canonical)
		h.render(w, r, loginPageData{Challenge: challenge, Error: genericLoginError})
		return
	default:
		h.logger.ErrorContext(r.Context(), "login: authenticator attempt failed", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	h.completeLogin(w, r, challenge, result.User.ID)
}

// emit is a no-op when h.emitter is nil, the same optional-dependency
// pattern identity.Authenticator's own account-axis limiter uses: a caller
// that has not wired an Emitter yet (most tests) gets no events, not a
// nil-pointer panic.
func (h *loginHandler) emit(r *http.Request, t audit.EventType, outcome audit.Outcome, subject string) {
	if h.emitter == nil {
		return
	}
	h.emitter.Emit(r.Context(), audit.Event{
		SchemaVersion: 1,
		Type:          t,
		Outcome:       outcome,
		Subject:       subject,
		// RemoteAddr is the raw socket peer, not realip-resolved — accurate
		// only when usher is directly exposed. Trusted-proxy-aware sourcing
		// (REQUIREMENTS §7.3's realip topology) is config.BuildKeyFunc's
		// concern for rate limiting; audit's SourceAddr does not yet share
		// it, which is a narrowing worth revisiting once main.go wires a
		// real topology, not a defect in this event's shape.
		SourceAddr: r.RemoteAddr,
		At:         h.now(),
	})
}

// completeLogin is RS-12b's dual rotation (session.RotateLogin, #20) plus
// recording the subject on a pending challenge, if one was threaded
// through. oldRawID is read before RotateLogin writes a new cookie — "" if
// this request carried no session cookie at all, which RotateLogin already
// treats as "nothing to delete."
func (h *loginHandler) completeLogin(w http.ResponseWriter, r *http.Request, challenge, subject string) {
	oldRawID, err := session.RawSessionID(r)
	if err != nil {
		oldRawID = ""
	}

	if _, err := session.RotateLogin(r.Context(), w, r, h.protector, h.sessions,
		oldRawID, subject, h.now(), h.idleTTL, h.absoluteTTL); err != nil {
		h.logger.ErrorContext(r.Context(), "login: rotate session", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	if challenge == "" {
		h.renderLoggedIn(w, r)
		return
	}
	h.proceedToConsent(w, r, challenge, subject, h.now())
}

func (h *loginHandler) render(w http.ResponseWriter, r *http.Request, data loginPageData) {
	if token, ok := csrf.Token(r); ok {
		data.CSRFToken = token
	}
	if nonce, ok := secureheaders.Nonce(r); ok {
		data.Nonce = nonce
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := h.loginTmpl.Execute(w, data); err != nil {
		h.logger.ErrorContext(r.Context(), "login: render template", "error", err)
	}
}

func (h *loginHandler) renderLoggedIn(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := h.loggedInTmpl.Execute(w, nil); err != nil {
		h.logger.ErrorContext(r.Context(), "login: render template", "error", err)
	}
}

// discardLogger is used where a caller does not supply one (most tests):
// an internal error during a test still has somewhere to go that is not
// the process's real log stream, and still satisfies loginHandler's field
// type. Production wiring passes a real *slog.Logger.
func discardLogger() *slog.Logger {
	return slog.New(slog.DiscardHandler)
}
