package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/JonasBorgesLM/usher/internal/oauth"
)

// FamilyStore implements oauth.FamilyStore over refresh_families and
// refresh_tokens (migrations/0001_initial_schema.sql). CreateFamily,
// Lookup (#35: issuance and hashed storage), Rotate and Revoke (#36:
// atomic reuse detection) are implemented here; RevokeAllForSubject
// panics rather than silently succeeding, the same convention
// pkg/tokenvalidator's own not-yet-implemented methods use — its real
// body, administrative and consent revocation, is #38's own scope.
type FamilyStore struct {
	pool *pgxpool.Pool
}

var _ oauth.FamilyStore = (*FamilyStore)(nil)

// NewFamilyStore wraps pool. The pool's schema must already be migrated
// (Migrate) — the same precondition UserStore and ConsentStore state.
func NewFamilyStore(pool *pgxpool.Pool) *FamilyStore {
	return &FamilyStore{pool: pool}
}

// CreateFamily implements oauth.FamilyStore: a new family row and its
// first token row, in one transaction, so a crash between the two can
// never leave a family with no token at all. The family's id is always
// generated by the database (refresh_families.id DEFAULT
// gen_random_uuid()) — f.ID and first.FamilyID are ignored on write, not
// validated against it, because no caller in this codebase has a UUID
// generator of its own to have produced one; a future caller that wants
// the generated id back has nowhere here to receive it (CreateFamily
// returns only error, matching ARCHITECTURE.md §2.2's own signature) and
// must recover it via Lookup against the token hash it already holds.
func (s *FamilyStore) CreateFamily(ctx context.Context, f oauth.Family, first oauth.RefreshToken) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("postgres: begin create family: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // a committed tx makes this a no-op; an error here is not actionable

	var familyID string
	err = tx.QueryRow(ctx,
		`INSERT INTO refresh_families (client_id, subject, scope, expires_at)
		 VALUES ($1, $2, $3, $4) RETURNING id`,
		f.ClientID, f.Subject, f.Scope, f.ExpiresAt,
	).Scan(&familyID)
	if err != nil {
		return fmt.Errorf("postgres: create refresh family: %w", err)
	}

	if _, err := tx.Exec(ctx,
		`INSERT INTO refresh_tokens (hash, family_id, expires_at) VALUES ($1, $2, $3)`,
		first.Hash[:], familyID, first.ExpiresAt,
	); err != nil {
		return fmt.Errorf("postgres: create first refresh token: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("postgres: commit create family: %w", err)
	}
	return nil
}

// Lookup implements oauth.FamilyStore: resolves hash to its owning Family
// and RefreshToken in one query, enforcing RF-12's two lifetimes itself —
// an idle-expired token (RefreshToken.ExpiresAt) or an absolute-expired
// family (Family.ExpiresAt) is ErrRefreshTokenNotFound, the same
// not-found-or-expired ambiguity oauth.ErrCodeNotFound already gives
// authorization codes. A revoked-but-unexpired family is NOT folded into
// that error: it is returned as-is, RevokedAt and RevokedReason populated,
// so a caller deciding what revocation means keeps that information.
func (s *FamilyStore) Lookup(ctx context.Context, hash [32]byte) (oauth.Family, oauth.RefreshToken, error) {
	var fam oauth.Family
	var tok oauth.RefreshToken
	var tokHash []byte
	var revokedReason *string

	err := s.pool.QueryRow(ctx,
		`SELECT f.id, f.client_id, f.subject, f.scope, f.created_at, f.expires_at, f.revoked_at, f.revoked_reason,
		        t.family_id, t.hash, t.issued_at, t.expires_at, t.consumed_at
		 FROM refresh_tokens t
		 JOIN refresh_families f ON f.id = t.family_id
		 WHERE t.hash = $1`,
		hash[:],
	).Scan(
		&fam.ID, &fam.ClientID, &fam.Subject, &fam.Scope, &fam.CreatedAt, &fam.ExpiresAt, &fam.RevokedAt, &revokedReason,
		&tok.FamilyID, &tokHash, &tok.IssuedAt, &tok.ExpiresAt, &tok.ConsumedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return oauth.Family{}, oauth.RefreshToken{}, oauth.ErrRefreshTokenNotFound
	}
	if err != nil {
		return oauth.Family{}, oauth.RefreshToken{}, fmt.Errorf("postgres: look up refresh token: %w", err)
	}
	if revokedReason != nil {
		fam.RevokedReason = *revokedReason
	}
	copy(tok.Hash[:], tokHash)

	now := time.Now()
	if !now.Before(tok.ExpiresAt) {
		return oauth.Family{}, oauth.RefreshToken{}, oauth.ErrRefreshTokenNotFound
	}
	if !now.Before(fam.ExpiresAt) {
		return oauth.Family{}, oauth.RefreshToken{}, oauth.ErrRefreshTokenNotFound
	}
	return fam, tok, nil
}

// Rotate implements oauth.FamilyStore: the single conditional UPDATE
// RS-11 requires, never a SELECT followed by one. docs/ARCHITECTURE.md
// §2.2's own "verbatim" query conditioned only on `consumed_at IS NULL`;
// this adds `f.revoked_at IS NULL` to the SAME statement (#36's own
// finding, recorded there) — without it, a family revoked for reuse on
// one token still lets its never-consumed successor rotate normally,
// since that row's own consumed_at was never touched. Folding the check
// into this one UPDATE, rather than a separate read beforehand, keeps
// RS-11's "atomic, never read-then-write" guarantee covering this case
// too, instead of opening a second TOCTOU window next to the one RS-11
// already closes.
//
// consumed == true: next is inserted in the same transaction as the
// UPDATE that won. consumed == false: nothing is inserted and nothing is
// committed — reuse (or a lost race, which this statement cannot tell
// apart, by ADR-0012's own design) is for the caller to act on
// (RotateRefreshToken, internal/oauth).
func (s *FamilyStore) Rotate(ctx context.Context, hash [32]byte, next oauth.RefreshToken) (bool, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return false, fmt.Errorf("postgres: begin rotate: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // a committed tx makes this a no-op; a lost race rolls back on purpose

	tag, err := tx.Exec(ctx,
		`UPDATE refresh_tokens t SET consumed_at = now()
		 FROM refresh_families f
		 WHERE t.hash = $1 AND t.consumed_at IS NULL AND f.id = t.family_id AND f.revoked_at IS NULL`,
		hash[:],
	)
	if err != nil {
		return false, fmt.Errorf("postgres: rotate refresh token: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return false, nil
	}

	if _, err := tx.Exec(ctx,
		`INSERT INTO refresh_tokens (hash, family_id, expires_at) VALUES ($1, $2, $3)`,
		next.Hash[:], next.FamilyID, next.ExpiresAt,
	); err != nil {
		return false, fmt.Errorf("postgres: insert next refresh token: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return false, fmt.Errorf("postgres: commit rotate: %w", err)
	}
	return true, nil
}

// Revoke implements oauth.FamilyStore, idempotently: a family already
// revoked keeps its original revoked_at/revoked_reason rather than
// having a later call overwrite either — RS-11's reuse detection and a
// later admin or consent revocation (#38) must not be able to clobber
// each other's record of which one actually happened first.
func (s *FamilyStore) Revoke(ctx context.Context, familyID, reason string) error {
	_, err := s.pool.Exec(ctx,
		`UPDATE refresh_families SET revoked_at = now(), revoked_reason = $1
		 WHERE id = $2 AND revoked_at IS NULL`,
		reason, familyID,
	)
	if err != nil {
		return fmt.Errorf("postgres: revoke refresh family: %w", err)
	}
	return nil
}

// RevokeAllForSubject implements oauth.FamilyStore. Implemented in #38.
func (s *FamilyStore) RevokeAllForSubject(ctx context.Context, subject, reason string) error {
	panic("postgres: FamilyStore.RevokeAllForSubject not implemented (#38)")
}
