package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/JonasBorgesLM/usher/internal/oauth"
)

// FamilyStore implements oauth.FamilyStore over refresh_families and
// refresh_tokens (migrations/0001_initial_schema.sql). Only CreateFamily
// and Lookup are implemented here (#35: issuance and hashed storage);
// Rotate, Revoke and RevokeAllForSubject panic rather than silently
// succeed, the same convention pkg/tokenvalidator's own not-yet-implemented
// methods use — their real bodies are #36 (atomic reuse detection), #37
// (client/grant binding) and #38 (revocation) respectively.
type FamilyStore struct {
	pool *pgxpool.Pool
}

var _ oauth.FamilyStore = (*FamilyStore)(nil)

// NewFamilyStore wraps pool. The pool's schema must already be migrated
// (Migrate) — the same precondition UserStore and ConsentStore state.
func NewFamilyStore(pool *pgxpool.Pool) *FamilyStore {
	return &FamilyStore{pool: pool}
}

// CreateFamily implements oauth.FamilyStore: a new family row and its
// first token row, in one transaction, so a crash between the two can
// never leave a family with no token at all. The family's id is always
// generated by the database (refresh_families.id DEFAULT
// gen_random_uuid()) — f.ID and first.FamilyID are ignored on write, not
// validated against it, because no caller in this codebase has a UUID
// generator of its own to have produced one; a future caller that wants
// the generated id back has nowhere here to receive it (CreateFamily
// returns only error, matching ARCHITECTURE.md §2.2's own signature) and
// must recover it via Lookup against the token hash it already holds.
func (s *FamilyStore) CreateFamily(ctx context.Context, f oauth.Family, first oauth.RefreshToken) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("postgres: begin create family: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // a committed tx makes this a no-op; an error here is not actionable

	var familyID string
	err = tx.QueryRow(ctx,
		`INSERT INTO refresh_families (client_id, subject, scope, expires_at)
		 VALUES ($1, $2, $3, $4) RETURNING id`,
		f.ClientID, f.Subject, f.Scope, f.ExpiresAt,
	).Scan(&familyID)
	if err != nil {
		return fmt.Errorf("postgres: create refresh family: %w", err)
	}

	if _, err := tx.Exec(ctx,
		`INSERT INTO refresh_tokens (hash, family_id, expires_at) VALUES ($1, $2, $3)`,
		first.Hash[:], familyID, first.ExpiresAt,
	); err != nil {
		return fmt.Errorf("postgres: create first refresh token: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("postgres: commit create family: %w", err)
	}
	return nil
}

// Lookup implements oauth.FamilyStore: resolves hash to its owning Family
// and RefreshToken in one query, enforcing RF-12's two lifetimes itself —
// an idle-expired token (RefreshToken.ExpiresAt) or an absolute-expired
// family (Family.ExpiresAt) is ErrRefreshTokenNotFound, the same
// not-found-or-expired ambiguity oauth.ErrCodeNotFound already gives
// authorization codes. A revoked-but-unexpired family is NOT folded into
// that error: it is returned as-is, RevokedAt and RevokedReason populated,
// so a caller deciding what revocation means keeps that information.
func (s *FamilyStore) Lookup(ctx context.Context, hash [32]byte) (oauth.Family, oauth.RefreshToken, error) {
	var fam oauth.Family
	var tok oauth.RefreshToken
	var tokHash []byte
	var revokedReason *string

	err := s.pool.QueryRow(ctx,
		`SELECT f.id, f.client_id, f.subject, f.scope, f.created_at, f.expires_at, f.revoked_at, f.revoked_reason,
		        t.family_id, t.hash, t.issued_at, t.expires_at, t.consumed_at
		 FROM refresh_tokens t
		 JOIN refresh_families f ON f.id = t.family_id
		 WHERE t.hash = $1`,
		hash[:],
	).Scan(
		&fam.ID, &fam.ClientID, &fam.Subject, &fam.Scope, &fam.CreatedAt, &fam.ExpiresAt, &fam.RevokedAt, &revokedReason,
		&tok.FamilyID, &tokHash, &tok.IssuedAt, &tok.ExpiresAt, &tok.ConsumedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return oauth.Family{}, oauth.RefreshToken{}, oauth.ErrRefreshTokenNotFound
	}
	if err != nil {
		return oauth.Family{}, oauth.RefreshToken{}, fmt.Errorf("postgres: look up refresh token: %w", err)
	}
	if revokedReason != nil {
		fam.RevokedReason = *revokedReason
	}
	copy(tok.Hash[:], tokHash)

	now := time.Now()
	if !now.Before(tok.ExpiresAt) {
		return oauth.Family{}, oauth.RefreshToken{}, oauth.ErrRefreshTokenNotFound
	}
	if !now.Before(fam.ExpiresAt) {
		return oauth.Family{}, oauth.RefreshToken{}, oauth.ErrRefreshTokenNotFound
	}
	return fam, tok, nil
}

// Rotate implements oauth.FamilyStore. Implemented in #36.
func (s *FamilyStore) Rotate(ctx context.Context, hash [32]byte, next oauth.RefreshToken) (bool, error) {
	panic("postgres: FamilyStore.Rotate not implemented (#36)")
}

// Revoke implements oauth.FamilyStore. Implemented in #38.
func (s *FamilyStore) Revoke(ctx context.Context, familyID, reason string) error {
	panic("postgres: FamilyStore.Revoke not implemented (#38)")
}

// RevokeAllForSubject implements oauth.FamilyStore. Implemented in #38.
func (s *FamilyStore) RevokeAllForSubject(ctx context.Context, subject, reason string) error {
	panic("postgres: FamilyStore.RevokeAllForSubject not implemented (#38)")
}
