// Command genkeys generates a fresh RS256 signing keyset for local
// development (ADR-0015: keys are a mounted directory, generated by an
// operator action, never committed to the repository or generated by
// usher itself at runtime). It is idempotent, the same shape cmd/seed's
// own doc comment states for itself: running it against a directory that
// already holds a keyset reports that and creates nothing new — keys.Load
// requires every key's windows to be internally consistent across the
// whole set, and silently adding a second key with arbitrary windows
// would be exactly the kind of malformed keyset Load exists to refuse.
package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"time"

	"github.com/JonasBorgesLM/usher/internal/config"
)

// keyMetadata mirrors internal/keys.go's own on-disk shape exactly —
// duplicated because that type is unexported to its own package.
type keyMetadata struct {
	KID       string    `json:"kid"`
	Algorithm string    `json:"algorithm"`
	PublishAt time.Time `json:"publish_at"`
	SignFrom  time.Time `json:"sign_from"`
	RetireAt  time.Time `json:"retire_at"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genkeys:", err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.Load(config.FromOSEnv)
	if err != nil {
		return fmt.Errorf("load configuration: %w", err)
	}
	return generateIfMissing(cfg.KeysDir)
}

// generateIfMissing is run's own body, pulled out so it takes a plain
// directory rather than needing a full Config to be testable -- it is
// not tested today (cmd/seed's own sibling tool sets the precedent that
// these small one-shot binaries are verified by running them, not by a
// unit test, since everything they call is already tested where it is
// defined), but keeping it free of config.Config costs nothing and
// leaves that door open.
func generateIfMissing(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("read keys directory %q: %w", dir, err)
		}
		if mkErr := os.MkdirAll(dir, 0o700); mkErr != nil {
			return fmt.Errorf("create keys directory %q: %w", dir, mkErr)
		}
	}
	for _, e := range entries {
		if filepath.Ext(e.Name()) == ".json" {
			slog.Info("genkeys: a keyset already exists -- doing nothing", "dir", dir, "found", e.Name())
			return nil
		}
	}

	kid := "dev-" + time.Now().UTC().Format("20060102150405")
	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return fmt.Errorf("generate RSA key: %w", err)
	}

	// Generous margins on both sides (RS-09): PublishAt well before
	// SignFrom, clearing any configured consumer_JWKS_cache_TTL up to
	// its own 1-hour bound (REQUIREMENTS RF-12) with room to spare;
	// RetireAt a full year out, since a single-key set has no successor
	// for keys.Load's pairwise retirement formula to check against.
	now := time.Now().UTC()
	meta := keyMetadata{
		KID:       kid,
		Algorithm: "RS256",
		PublishAt: now.Add(-24 * time.Hour),
		SignFrom:  now.Add(-time.Hour),
		RetireAt:  now.AddDate(1, 0, 0),
	}
	metaBytes, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal key metadata: %w", err)
	}
	if writeErr := os.WriteFile(filepath.Join(dir, kid+".json"), metaBytes, 0o600); writeErr != nil {
		return fmt.Errorf("write key metadata: %w", writeErr)
	}

	pkcs8, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return fmt.Errorf("marshal private key: %w", err)
	}
	pemBytes := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: pkcs8})
	if writeErr := os.WriteFile(filepath.Join(dir, kid+".pem"), pemBytes, 0o600); writeErr != nil {
		return fmt.Errorf("write private key: %w", writeErr)
	}

	slog.Info("genkeys: generated a new signing key", "kid", kid, "dir", dir)
	return nil
}
